package com.mola.cmd.proxy.app.acp.team.event;

public enum TeamEventType {
    TEAM_CREATE_ACCEPTED,
    TEAM_READY,
    TEAM_CREATE_FAILED,
    TEAM_RECOVERY_STARTED,
    TEAM_RECOVERED,
    TEAM_RECOVERY_FAILED,
    TEAM_DELETE_ACCEPTED,
    TEAM_DELETE_FAILED,
    TEAM_STATE_CHANGED,
    MEMBER_STATE_CHANGED,
    MEMBER_SESSION_CHANGED,
    MESSAGE_CHUNK,
    MESSAGE_COMPLETE,
    MESSAGE_ERROR,
    TOOL_CALL,
    TALK_TO_SEND,
    TALK_TO_RECEIVE,
    TALK_TO_QUEUED,
    TALK_TO_REJECTED,
    TALK_TO_ROUTE_REQUEST,
    SCHEDULE_EVENT,
    SUB_AGENT_EVENT,
    COMPACTION_EVENT,
    TEAM_DELETED,
    TEAM_SNAPSHOT_READY
}
