package com.mola.cmd.proxy.app.acp.team.model;

public enum TeamErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    NOT_FOUND,
    TEAM_NOT_READY,
    MEMBER_BUSY,
    QUOTA_EXCEEDED,
    IDEMPOTENCY_CONFLICT,
    VERSION_CONFLICT,
    SOURCE_ROBOT_NOT_FOUND,
    SOURCE_ROBOT_MISMATCH,
    CLIENT_START_FAILED,
    CLIENT_CLOSED,
    MEMORY_NOT_ENABLED,
    TEAM_DELETING,
    INBOX_FULL,
    INTERNAL_ERROR
}
